remote: false

experience_level:
 internship: false
 entry: false
 associate: false
 mid-senior level: true
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: false
 part-time: false
 temporary: false
 internship: false
 other: false
 volunteer: false

date:
 all time: false
 month: true
 week: false
 24 hours: false

positions:
  - Software Engineer
#  - Lead Software Engineer
#  - Software Engineer Backend
#  - Senior Software Engineer
#  - Backend Engineer
#  - Backend Developer
#  - Fullstack Engineer
#  - SDE 2

locations:
  - Bengaluru

apply_once_at_company: false

distance: 100

company_blacklist:
  - Cred
  - Udaan
  - Google
  - Toast


title_blacklist:

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 1000
  
llm_model_type: openai
llm_model: gpt-4o-mini 
# llm_api_url: https://api.pawan.krd/cosmosrp/v1 this field is optional
